apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-namespace.yaml
  - 02-deployments.yaml
  - 03-services.yaml
  - ../hospital-cert/01-ca-certificate.yaml
  - ../hospital-cert/02-ca-issuer.yaml
  - ../hospital-cert/03-app-certificate.yaml
  - ../hospital-gateway/01-gateway-class.yaml
  - ../hospital-gateway/02-gateway.yaml
  - ../hospital-gateway/03-routes.yaml
  - ../hospital-gateway/04-envoy-proxy.yaml
