apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-app
  namespace: argocd
  labels:
    app: hospital-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/chandrasekhar7/kubernetes-gatewayapi.git' # TODO: Replace with your repository URL
    targetRevision: minikube1
    path: hospital-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hospital-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
